language: ruby
rvm:
  - 2.6

before_install:
  gem update --system

script:
  tasks/test

# deploy changes on master to lich repo
deploy:
  provider: script
  script: tasks/sync
  skip_cleanup: true
  on:
    branch: master