language: ruby
rvm:
- 2.6
before_install:
- gem update --system
- gem install gem-release
script:
- tasks/verify-git-range $TRAVIS_COMMIT_RANGE
after_success:
- tasks/prepare-deploy gsiv
- export TRAVIS_TAG=${TRAVIS_TAG:-$(tasks/tag)}
- if [ -z "$TRAVIS_TAG" ]; then echo "skipping release"; else git tag $TRAVIS_TAG;
  fi
deploy:
  provider: rubygems
  api_key:
    secure: LC0AD4g/Ew87/86C1joTvOjqgf6VuSD/5RcHau/ye/nkLlw9ljx3nxkoEIxrDKrZlGkrHjI3ziL0YQpWkQAiF1pr6cNMg61Nb8IeMGm93GLvuoJNh+dIX6QnLgMF71jpCmmlnMqQ8Fu4USqzO+I97dBJYGxUWrczcu514r2hLJXvYbeRwkLG2pJiXIcqgiwcIM1v1dNsnb8At6HTwrnueedJO/GLbM/yTyW8As9a5ytBqL8guUi0yW/SAC7idxoRiQ9poX9ZhLridUfwCS/NUgQB8CTiKNjTMGRzoIMjkDAJaOL9iztfCDcwS9isuAkR3Cx9bt8MNVwZA9iOf9DYZzYq+ffZ2YNVBRXrOgyakaSfixPGoswr95bQNxx0hVxq/EmqHyNDoiwydfJ/LcLEkUWHRqlGbVBMZ5c5ifERrk05EXejR8ofxzy2LLsMmCHm76QB3fxPxxLBxNBykQTwQYdj3G1LXq/BxvAEQ9ydAEh/BsXEXkXNxgySbNyB9R9ZG4UsvhoNB7DjAiLqNm/X1THyTiX5jqtzuYlxNrko9rV4tr/EFNSetKJwnEYhbXcu92P6XSyj8XD2uW5LFxg49R2em9oUKmD9ajjjZKp5qPBNH0HYJ5f8FXy5M7/6fgveKm8NihDyEQtmfAZBgbYZAEbFw7twN/FUu736BHxxGFE=
  gem: eol-cartograph
  on:
    tags: true
    repo: elanthia-online/cartograph
    branches:
      only:
        - master
  skip_cleanup: 'true'
