#!/usr/bin/env ruby
require 'digest'
require_relative './common/cartograph'
if File.exists? Cartograph.cartograph_file
  $stdout.puts "map/gsiv/%s" % Digest::MD5.hexdigest(File.read(Cartograph.cartograph_file))
else
  exit 0
end