#!/usr/bin/env ruby
require 'digest'
require_relative './common/cartograph'
require_relative '../util/opts'
require_relative '../lib/eol-cartograph/version'

if File.exists?(Cartograph.cartograph_file) or Opts.force
  $stdout.puts Cartograph::VERSION
else
  exit 0
end